//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseVidTest
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public string Video { get; set; }
        public string Title { get; set; }
    
        public virtual CourseTest CourseTest { get; set; }
    }
}
