//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Oddhoyon_AdminPanelEntities : DbContext
    {
        public Oddhoyon_AdminPanelEntities()
            : base("name=Oddhoyon_AdminPanelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Chapter> tbl_Chapter { get; set; }
        public virtual DbSet<tbl_ChapterContent> tbl_ChapterContent { get; set; }
        public virtual DbSet<tbl_ChapterDetails> tbl_ChapterDetails { get; set; }
        public virtual DbSet<tbl_Class> tbl_Class { get; set; }
        public virtual DbSet<tbl_PublicExam> tbl_PublicExam { get; set; }
        public virtual DbSet<tbl_PublicExamSuggestion> tbl_PublicExamSuggestion { get; set; }
        public virtual DbSet<tbl_TextBook> tbl_TextBook { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<tbl_SuggestionLists> tbl_SuggestionLists { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<PostCategory> PostCategories { get; set; }
        public virtual DbSet<CourseTest> CourseTests { get; set; }
        public virtual DbSet<CourseVidTest> CourseVidTests { get; set; }
        public virtual DbSet<tbl_ChapQuestion> tbl_ChapQuestion { get; set; }
        public virtual DbSet<tbl_SubChapExam> tbl_SubChapExam { get; set; }
        public virtual DbSet<tbl_UserAnsOfChap> tbl_UserAnsOfChap { get; set; }
        public virtual DbSet<tbl_AnonymousMsg> tbl_AnonymousMsg { get; set; }
        public virtual DbSet<CourseEnrolled> CourseEnrolleds { get; set; }
    }
}
