//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChapterDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ChapterDetails()
        {
            this.tbl_ChapterContent = new HashSet<tbl_ChapterContent>();
        }
    
        public int ChapterDetailsID { get; set; }
        public int ChapterID { get; set; }
        public string ChapterName { get; set; }
    
        public virtual tbl_Chapter tbl_Chapter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ChapterContent> tbl_ChapterContent { get; set; }
    }
}
