//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TextBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TextBook()
        {
            this.tbl_Chapter = new HashSet<tbl_Chapter>();
        }
    
        public int BookID { get; set; }
        public string BookName { get; set; }
        public string BookType { get; set; }
        public Nullable<System.DateTime> YearOfEdition { get; set; }
        public string Description { get; set; }
        public int ClassID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Chapter> tbl_Chapter { get; set; }
        public virtual tbl_Class tbl_Class { get; set; }
    }
}
