//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChapterContent
    {
        public int ChapterContentID { get; set; }
        public int ChapterDetailsID { get; set; }
        public string TopicTitle { get; set; }
        public string TopicDetails { get; set; }
        public string Qst { get; set; }
        public string Ans { get; set; }
        public string Image { get; set; }
        public string Video { get; set; }
    
        public virtual tbl_ChapterDetails tbl_ChapterDetails { get; set; }
    }
}
