//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserAnsOfChap
    {
        public int Id { get; set; }
        public string UserAns { get; set; }
        public Nullable<int> QstId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual tbl_ChapQuestion tbl_ChapQuestion { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
