//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PublicExamSuggestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PublicExamSuggestion()
        {
            this.tbl_SuggestionLists = new HashSet<tbl_SuggestionLists>();
        }
    
        public int SuggestionID { get; set; }
        public Nullable<int> PublicExamID { get; set; }
        public string SubjectName { get; set; }
        public string Image { get; set; }
    
        public virtual tbl_PublicExam tbl_PublicExam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SuggestionLists> tbl_SuggestionLists { get; set; }
    }
}
